/* SPDX-License-Identifier: GPL-3.0-only
 * BCM2712 PixelValve VSync support for the display-only driver.
 *
 * This file intentionally does not program display modes, HVS lists, HDMI, or
 * V3D. It only uses the PixelValve VFP-start interrupt already generated by
 * the firmware-configured scanout, and derives scan-line position from that
 * real hardware VSync anchor plus the validated firmware timing.
 */
#include "display.h"

#define RP_PV_MMIO_BYTES              0x100u
#define RP_PV0_PHYS                   0x107c410000ULL
#define RP_PV1_PHYS                   0x107c411000ULL
#define RP_PV_V_CONTROL               0x04u
#define RP_PV_VCONTROL_VIDEN          (1u << 0)
#define RP_PV_INTEN                   0x24u
#define RP_PV_INTSTAT                 0x28u
#define RP_PV_INT_VFP_START           (1u << 7)

#define RP_VSYNC_PHASE_NONE            0L
#define RP_VSYNC_PHASE_PROVISIONAL     1L
#define RP_VSYNC_PHASE_HARDWARE        2L
#define RP_VSYNC_CONTROL_PERSIST_MASK   63ULL

static volatile ULONG *RpPvRegister(RP_ADAPTER *a, ULONG offset)
{
    return (volatile ULONG *)((volatile UCHAR *)a->PixelValveRegs + offset);
}

static VOID RpWriteDeviceDword(RP_ADAPTER *a, PCWSTR valueName, ULONG value)
{
    HANDLE key;
    UNICODE_STRING name;

    if (!a || !a->Pdo ||
        !NT_SUCCESS(IoOpenDeviceRegistryKey(a->Pdo, PLUGPLAY_REGKEY_DEVICE,
                                             KEY_SET_VALUE, &key))) {
        return;
    }

    RtlInitUnicodeString(&name, valueName);
    (VOID)ZwSetValueKey(key, &name, 0, REG_DWORD, &value, sizeof(value));
    ZwClose(key);
}

static VOID RpRecordVSyncCounters(RP_ADAPTER *a)
{
    ULONGLONG count;
    ULONGLONG queries;
    ULONGLONG provisionalQueries;
    ULONGLONG requests;
    ULONGLONG enables;
    ULONGLONG disables;
    ULONGLONG fallbacks;
    ULONGLONG anchor;
    ULONG phase;

    if (!a) return;
    count = (ULONGLONG)InterlockedCompareExchange64(&a->VSyncCount, 0, 0);
    queries = (ULONGLONG)InterlockedCompareExchange64(&a->ScanLineQueries, 0, 0);
    provisionalQueries = (ULONGLONG)InterlockedCompareExchange64(
        &a->VSyncProvisionalScanLineQueries, 0, 0);
    requests = (ULONGLONG)InterlockedCompareExchange64(
        &a->VSyncControlRequests, 0, 0);
    enables = (ULONGLONG)InterlockedCompareExchange64(
        &a->VSyncControlEnableRequests, 0, 0);
    disables = (ULONGLONG)InterlockedCompareExchange64(
        &a->VSyncControlDisableRequests, 0, 0);
    fallbacks = (ULONGLONG)InterlockedCompareExchange64(
        &a->VSyncControlDirectFallbacks, 0, 0);
    anchor = (ULONGLONG)InterlockedCompareExchange64(&a->LastVSyncQpc, 0, 0);
    phase = (ULONG)InterlockedCompareExchange(&a->VSyncPhaseSource, 0, 0);

    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncInterruptsLow", (ULONG)count);
    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncInterruptsHigh", (ULONG)(count >> 32));
    RpWriteDeviceDword(a, L"Rpi5DisplayScanLineQueriesLow", (ULONG)queries);
    RpWriteDeviceDword(a, L"Rpi5DisplayScanLineQueriesHigh", (ULONG)(queries >> 32));
    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncProvisionalQueriesLow",
                       (ULONG)provisionalQueries);
    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncProvisionalQueriesHigh",
                       (ULONG)(provisionalQueries >> 32));
    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncControlRequestsLow", (ULONG)requests);
    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncControlRequestsHigh",
                       (ULONG)(requests >> 32));
    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncControlEnableRequestsLow",
                       (ULONG)enables);
    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncControlEnableRequestsHigh",
                       (ULONG)(enables >> 32));
    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncControlDisableRequestsLow",
                       (ULONG)disables);
    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncControlDisableRequestsHigh",
                       (ULONG)(disables >> 32));
    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncControlFallbacksLow",
                       (ULONG)fallbacks);
    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncControlFallbacksHigh",
                       (ULONG)(fallbacks >> 32));
    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncPhaseSource", phase);
    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncAnchorReady",
                       (phase == RP_VSYNC_PHASE_HARDWARE && count != 0) ? 1u : 0u);
    if (phase == RP_VSYNC_PHASE_HARDWARE && count != 0) {
        RpWriteDeviceDword(a, L"Rpi5DisplayVSyncAnchorQpcLow", (ULONG)anchor);
        RpWriteDeviceDword(a, L"Rpi5DisplayVSyncAnchorQpcHigh",
                           (ULONG)(anchor >> 32));
    }
}

static BOOLEAN RpShouldPersistControlResult(
    RP_ADAPTER *a,
    BOOLEAN enableInterrupt,
    BOOLEAN usedDirectFallback,
    NTSTATUS finalStatus)
{
    ULONGLONG requests;

    if (!a) return FALSE;

    /*
     * 0.1.13 persisted roughly thirty registry DWORDs on every VSync
     * enable/disable transition. Windows toggles VSync control routinely, so
     * that diagnostic path became ongoing registry I/O during normal desktop
     * use. Preserve the first enable/disable evidence, every failure/fallback,
     * and a periodic snapshot instead.
     */
    if (!NT_SUCCESS(finalStatus) || usedDirectFallback) return TRUE;

    if (enableInterrupt) {
        if (InterlockedCompareExchange(
                &a->VSyncEnableEvidencePersisted, 1, 0) == 0) {
            return TRUE;
        }
    } else {
        if (InterlockedCompareExchange(
                &a->VSyncDisableEvidencePersisted, 1, 0) == 0) {
            return TRUE;
        }
    }

    requests = (ULONGLONG)InterlockedCompareExchange64(
        &a->VSyncControlRequests, 0, 0);
    return (requests & RP_VSYNC_CONTROL_PERSIST_MASK) == 0;
}

static VOID RpRecordControlInterruptResult(
    RP_ADAPTER *a,
    DXGK_INTERRUPT_TYPE interruptType,
    BOOLEAN enableInterrupt,
    NTSTATUS synchronizeStatus,
    BOOLEAN synchronizeReturn,
    BOOLEAN usedDirectFallback,
    NTSTATUS finalStatus)
{
    ULONG inten = 0;
    ULONG intstat = 0;

    if (!a || !RpShouldPersistControlResult(
            a, enableInterrupt, usedDirectFallback, finalStatus)) {
        return;
    }

    RpRecordVSyncCounters(a);
    if (a->PixelValveRegs) {
        inten = READ_REGISTER_ULONG((PULONG)RpPvRegister(a, RP_PV_INTEN));
        intstat = READ_REGISTER_ULONG((PULONG)RpPvRegister(a, RP_PV_INTSTAT));
    }

    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncLastControlType",
                       (ULONG)interruptType);
    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncLastControlEnable",
                       enableInterrupt ? 1u : 0u);
    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncLastControlSyncStatus",
                       (ULONG)synchronizeStatus);
    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncLastControlSyncReturn",
                       synchronizeReturn ? 1u : 0u);
    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncLastControlFallback",
                       usedDirectFallback ? 1u : 0u);
    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncLastControlStatus",
                       (ULONG)finalStatus);
    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncLastControlPvInten", inten);
    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncLastControlPvIntstat", intstat);
    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncInterruptEnabled",
                       (ULONG)InterlockedCompareExchange(
                           &a->VSyncInterruptEnabled, 0, 0));

    if (enableInterrupt) {
        RpWriteDeviceDword(a, L"Rpi5DisplayVSyncLastEnableType",
                           (ULONG)interruptType);
        RpWriteDeviceDword(a, L"Rpi5DisplayVSyncLastEnableSyncStatus",
                           (ULONG)synchronizeStatus);
        RpWriteDeviceDword(a, L"Rpi5DisplayVSyncLastEnableSyncReturn",
                           synchronizeReturn ? 1u : 0u);
        RpWriteDeviceDword(a, L"Rpi5DisplayVSyncLastEnableFallback",
                           usedDirectFallback ? 1u : 0u);
        RpWriteDeviceDword(a, L"Rpi5DisplayVSyncLastEnableStatus",
                           (ULONG)finalStatus);
        RpWriteDeviceDword(a, L"Rpi5DisplayVSyncLastEnablePvInten", inten);
        RpWriteDeviceDword(a, L"Rpi5DisplayVSyncLastEnablePvIntstat", intstat);
        RpWriteDeviceDword(a, L"Rpi5DisplayVSyncLastEnableActive",
                           (ULONG)InterlockedCompareExchange(&a->Active, 0, 0));
        RpWriteDeviceDword(a, L"Rpi5DisplayVSyncLastEnableHardwareReady",
                           a->VSyncHardwareReady ? 1u : 0u);
    } else {
        RpWriteDeviceDword(a, L"Rpi5DisplayVSyncLastDisableType",
                           (ULONG)interruptType);
        RpWriteDeviceDword(a, L"Rpi5DisplayVSyncLastDisableSyncStatus",
                           (ULONG)synchronizeStatus);
        RpWriteDeviceDword(a, L"Rpi5DisplayVSyncLastDisableSyncReturn",
                           synchronizeReturn ? 1u : 0u);
        RpWriteDeviceDword(a, L"Rpi5DisplayVSyncLastDisableFallback",
                           usedDirectFallback ? 1u : 0u);
        RpWriteDeviceDword(a, L"Rpi5DisplayVSyncLastDisableStatus",
                           (ULONG)finalStatus);
        RpWriteDeviceDword(a, L"Rpi5DisplayVSyncLastDisablePvInten", inten);
        RpWriteDeviceDword(a, L"Rpi5DisplayVSyncLastDisablePvIntstat", intstat);
    }
}

BOOLEAN RpVSyncRegistrationAvailable(VOID)
{
    RP_DISPLAY_HANDOFF handoff;
    RP_HANDOFF_SOURCE source = RpHandoffNone;
    ULONG attributes = 0;
    NTSTATUS status;

    RtlZeroMemory(&handoff, sizeof(handoff));
    status = RpReadDisplayHandoff(
        &handoff,
        &attributes,
        &source,
        0,
        0);
    if (!NT_SUCCESS(status)) {
        RP_LOG("VSync registration handoff unavailable status=0x%08lx\n", status);
        return FALSE;
    }

    RP_LOG("VSync registration handoff source=%u display=%lu clockKHz=%lu total=%ux%u\n",
           (UINT)source, handoff.display_number, handoff.timing.clock_khz,
           handoff.timing.htotal, handoff.timing.vtotal);

    /* This first hardware implementation is intentionally limited to Pi 5 HDMI. */
    return handoff.display_number == 2u || handoff.display_number == 7u;
}

static PCM_PARTIAL_RESOURCE_DESCRIPTOR RpFindMemoryResource(
    PCM_RESOURCE_LIST list,
    ULONGLONG expectedBase,
    ULONG minimumLength)
{
    ULONG fullIndex;
    ULONG partialIndex;

    if (!list) return NULL;

    for (fullIndex = 0; fullIndex < list->Count; ++fullIndex) {
        PCM_FULL_RESOURCE_DESCRIPTOR full = &list->List[fullIndex];
        PCM_PARTIAL_RESOURCE_LIST partial = &full->PartialResourceList;

        for (partialIndex = 0; partialIndex < partial->Count; ++partialIndex) {
            PCM_PARTIAL_RESOURCE_DESCRIPTOR descriptor =
                &partial->PartialDescriptors[partialIndex];

            if (descriptor->Type != CmResourceTypeMemory) continue;
            if ((ULONGLONG)descriptor->u.Memory.Start.QuadPart != expectedBase) continue;
            if (descriptor->u.Memory.Length < minimumLength) continue;
            return descriptor;
        }
    }

    return NULL;
}

NTSTATUS RpVSyncInitialize(RP_ADAPTER *a, PCM_RESOURCE_LIST resources)
{
    ULONGLONG expectedBase;
    PCM_PARTIAL_RESOURCE_DESCRIPTOR descriptor;
    LARGE_INTEGER frequency;
    LARGE_INTEGER seed;
    ULONG vcontrol;

    if (!a || !a->VSyncAdvertised || !a->FirmwareTimingValid) {
        return STATUS_DEVICE_CONFIGURATION_ERROR;
    }

    if (a->FirmwareDisplay.display_number == 2u) {
        expectedBase = RP_PV0_PHYS;
        a->PixelValveIndex = 0;
    } else if (a->FirmwareDisplay.display_number == 7u) {
        expectedBase = RP_PV1_PHYS;
        a->PixelValveIndex = 1;
    } else {
        return STATUS_NOT_SUPPORTED;
    }

    descriptor = RpFindMemoryResource(resources, expectedBase, RP_PV_MMIO_BYTES);
    if (!descriptor) {
        RP_LOG("VSync: assigned PixelValve MMIO resource 0x%llx not found\n",
               expectedBase);
        return STATUS_DEVICE_CONFIGURATION_ERROR;
    }

    a->PixelValveRegs = MmMapIoSpaceEx(
        descriptor->u.Memory.Start,
        RP_PV_MMIO_BYTES,
        PAGE_READWRITE | PAGE_NOCACHE);
    if (!a->PixelValveRegs) {
        return STATUS_NO_MEMORY;
    }
    a->PixelValveBytes = RP_PV_MMIO_BYTES;

    vcontrol = READ_REGISTER_ULONG((PULONG)RpPvRegister(a, RP_PV_V_CONTROL));
    if ((vcontrol & RP_PV_VCONTROL_VIDEN) == 0) {
        RP_LOG("VSync: PixelValve%lu is not scanning out (V_CONTROL=0x%08lx)\n",
               a->PixelValveIndex, vcontrol);
        MmUnmapIoSpace(a->PixelValveRegs, a->PixelValveBytes);
        a->PixelValveRegs = NULL;
        a->PixelValveBytes = 0;
        return STATUS_DEVICE_NOT_READY;
    }

    /* Start with the hardware interrupt disabled until dxgkrnl requests it. */
    WRITE_REGISTER_ULONG(
        (PULONG)RpPvRegister(a, RP_PV_INTEN),
        READ_REGISTER_ULONG((PULONG)RpPvRegister(a, RP_PV_INTEN)) &
            ~RP_PV_INT_VFP_START);
    WRITE_REGISTER_ULONG((PULONG)RpPvRegister(a, RP_PV_INTSTAT),
                         RP_PV_INT_VFP_START);
    KeMemoryBarrier();

    seed = KeQueryPerformanceCounter(&frequency);
    a->QpcFrequency = frequency.QuadPart;
    if (a->QpcFrequency <= 0 || seed.QuadPart <= 0) {
        MmUnmapIoSpace(a->PixelValveRegs, a->PixelValveBytes);
        a->PixelValveRegs = NULL;
        a->PixelValveBytes = 0;
        return STATUS_DEVICE_CONFIGURATION_ERROR;
    }

    /*
     * Windows can query scan-line position before the first hardware VFP edge.
     * Seed a timing-only provisional phase from the validated firmware mode so
     * GetScanLine can answer immediately. This is never reported as a hardware
     * VSync anchor; the ISR replaces it with the first real VFP_START edge.
     */
    InterlockedExchange64(&a->LastVSyncQpc, seed.QuadPart);
    InterlockedExchange(&a->VSyncPhaseSource, RP_VSYNC_PHASE_PROVISIONAL);
    InterlockedExchange(&a->VSyncInterruptEnabled, 0);
    InterlockedExchange(&a->VSyncAnchorReported, 0);
    InterlockedExchange(&a->VSyncProvisionalReported, 0);
    InterlockedExchange64(&a->VSyncCount, 0);
    InterlockedExchange64(&a->ScanLineQueries, 0);
    InterlockedExchange64(&a->VSyncProvisionalScanLineQueries, 0);
    InterlockedExchange64(&a->VSyncControlRequests, 0);
    InterlockedExchange64(&a->VSyncControlEnableRequests, 0);
    InterlockedExchange64(&a->VSyncControlDisableRequests, 0);
    InterlockedExchange64(&a->VSyncControlDirectFallbacks, 0);
    InterlockedExchange(&a->VSyncEnableEvidencePersisted, 0);
    InterlockedExchange(&a->VSyncDisableEvidencePersisted, 0);
    a->VSyncHardwareReady = TRUE;

    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncAdvertised", 1);
    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncHardwareReady", 1);
    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncInterruptEnabled", 0);
    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncProvisionalPhaseReady", 1);
    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncProvisionalSeedQpcLow",
                       (ULONG)seed.QuadPart);
    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncProvisionalSeedQpcHigh",
                       (ULONG)((ULONGLONG)seed.QuadPart >> 32));
    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncLastControlType", MAXULONG);
    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncLastControlSyncStatus",
                       (ULONG)STATUS_PENDING);
    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncLastControlStatus",
                       (ULONG)STATUS_PENDING);
    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncLastEnableType", MAXULONG);
    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncLastEnableSyncStatus",
                       (ULONG)STATUS_PENDING);
    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncLastEnableStatus",
                       (ULONG)STATUS_PENDING);
    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncLastDisableType", MAXULONG);
    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncLastDisableSyncStatus",
                       (ULONG)STATUS_PENDING);
    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncLastDisableStatus",
                       (ULONG)STATUS_PENDING);
    RpWriteDeviceDword(a, L"Rpi5DisplayPixelValveIndex", a->PixelValveIndex);
    RpWriteDeviceDword(a, L"Rpi5DisplayPixelValvePhysLow", (ULONG)expectedBase);
    RpWriteDeviceDword(a, L"Rpi5DisplayPixelValvePhysHigh",
                       (ULONG)(expectedBase >> 32));
    RpRecordVSyncCounters(a);

    RP_LOG("VSync: hardware ready with provisional scanline phase display=%lu pv=%lu base=0x%llx qpcHz=%lld seed=%lld; waiting for Windows-enabled first VFP edge\n",
           a->FirmwareDisplay.display_number, a->PixelValveIndex,
           expectedBase, a->QpcFrequency, seed.QuadPart);
    return STATUS_SUCCESS;
}

typedef struct RP_VSYNC_CONTROL_CONTEXT {
    RP_ADAPTER *Adapter;
    BOOLEAN Enable;
    LONG64 ProvisionalQpc;
} RP_VSYNC_CONTROL_CONTEXT;

static BOOLEAN RpSetVSyncSynchronized(PVOID context)
{
    RP_VSYNC_CONTROL_CONTEXT *control = (RP_VSYNC_CONTROL_CONTEXT *)context;
    RP_ADAPTER *a;
    ULONG enable;

    if (!control || !control->Adapter) return FALSE;
    a = control->Adapter;
    if (!a->PixelValveRegs) return FALSE;

    enable = READ_REGISTER_ULONG((PULONG)RpPvRegister(a, RP_PV_INTEN));
    if (control->Enable) {
        if (control->ProvisionalQpc <= 0) return FALSE;

        /*
         * Publish the software state before unmasking VFP_START. Otherwise a
         * first edge can race the old 0.1.11 ordering and the ISR will reject
         * the interrupt because VSyncInterruptEnabled is still zero.
         */
        InterlockedExchange64(&a->LastVSyncQpc, control->ProvisionalQpc);
        InterlockedExchange(&a->VSyncPhaseSource, RP_VSYNC_PHASE_PROVISIONAL);
        /*
         * VSyncAnchorReported is a per-session one-shot diagnostic latch.
         * Re-enabling VSync must not re-arm registry/log persistence.
         */
        WRITE_REGISTER_ULONG((PULONG)RpPvRegister(a, RP_PV_INTSTAT),
                             RP_PV_INT_VFP_START);
        InterlockedExchange(&a->VSyncInterruptEnabled, 1);
        KeMemoryBarrier();
        WRITE_REGISTER_ULONG((PULONG)RpPvRegister(a, RP_PV_INTEN),
                             enable | RP_PV_INT_VFP_START);
        KeMemoryBarrier();
    } else {
        WRITE_REGISTER_ULONG((PULONG)RpPvRegister(a, RP_PV_INTEN),
                             enable & ~RP_PV_INT_VFP_START);
        WRITE_REGISTER_ULONG((PULONG)RpPvRegister(a, RP_PV_INTSTAT),
                             RP_PV_INT_VFP_START);
        KeMemoryBarrier();
        InterlockedExchange(&a->VSyncInterruptEnabled, 0);
        /*
         * Keep the last timing phase for diagnostics/GetScanLine. A later
         * enable always reseeds a provisional phase before unmasking the IRQ.
         */
    }
    return TRUE;
}

static BOOLEAN RpDisableVSyncSynchronized(PVOID context)
{
    RP_VSYNC_CONTROL_CONTEXT control;
    control.Adapter = (RP_ADAPTER *)context;
    control.Enable = FALSE;
    control.ProvisionalQpc = 0;
    return RpSetVSyncSynchronized(&control);
}

VOID RpVSyncShutdown(RP_ADAPTER *a)
{
    BOOLEAN synchronized = FALSE;
    ULONG enabledBeforeStop;
    ULONG intenBeforeStop;
    ULONG intstatBeforeStop;

    if (!a || !a->PixelValveRegs) return;

    enabledBeforeStop = (ULONG)InterlockedCompareExchange(
        &a->VSyncInterruptEnabled, 0, 0);
    intenBeforeStop = READ_REGISTER_ULONG(
        (PULONG)RpPvRegister(a, RP_PV_INTEN));
    intstatBeforeStop = READ_REGISTER_ULONG(
        (PULONG)RpPvRegister(a, RP_PV_INTSTAT));
    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncInterruptEnabledBeforeStop",
                       enabledBeforeStop);
    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncPvIntenBeforeStop",
                       intenBeforeStop);
    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncPvIntstatBeforeStop",
                       intstatBeforeStop);
    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncPhaseSourceAtStop",
                       (ULONG)InterlockedCompareExchange(
                           &a->VSyncPhaseSource, 0, 0));
    RpRecordVSyncCounters(a);

    if (a->Dxgk.DxgkCbSynchronizeExecution && a->Dxgk.DeviceHandle) {
        NTSTATUS status = a->Dxgk.DxgkCbSynchronizeExecution(
            a->Dxgk.DeviceHandle,
            RpDisableVSyncSynchronized,
            a,
            0,
            &synchronized);
        if (!NT_SUCCESS(status) || !synchronized) {
            RpDisableVSyncSynchronized(a);
        }
    } else {
        RpDisableVSyncSynchronized(a);
    }

    a->VSyncHardwareReady = FALSE;
    MmUnmapIoSpace(a->PixelValveRegs, a->PixelValveBytes);
    a->PixelValveRegs = NULL;
    a->PixelValveBytes = 0;
    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncHardwareReady", 0);
    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncInterruptEnabled", 0);
    /*
     * Do not erase AnchorReady/counters here. They are post-mortem evidence
     * for the session that Windows just stopped.
     */
}

NTSTATUS APIENTRY RpControlInterrupt(
    CONST HANDLE context,
    CONST DXGK_INTERRUPT_TYPE interruptType,
    BOOLEAN enableInterrupt)
{
    RP_ADAPTER *a = (RP_ADAPTER *)context;
    RP_VSYNC_CONTROL_CONTEXT control;
    BOOLEAN synchronized = FALSE;
    BOOLEAN applied = FALSE;
    BOOLEAN usedDirectFallback = FALSE;
    NTSTATUS synchronizeStatus = STATUS_NOT_SUPPORTED;
    NTSTATUS finalStatus;
    LARGE_INTEGER seed;

    PAGED_CODE();

    if (!a) return STATUS_INVALID_PARAMETER;

    InterlockedIncrement64(&a->VSyncControlRequests);
    if (enableInterrupt) {
        InterlockedIncrement64(&a->VSyncControlEnableRequests);
    } else {
        InterlockedIncrement64(&a->VSyncControlDisableRequests);
    }

    /*
     * The generic DxgkDdiControlInterrupt documentation describes
     * DXGK_INTERRUPT_CRTC_VSYNC (3). On the Windows 11 KMDOD path exercised by
     * this driver, dxgkrnl actually requests DXGK_INTERRUPT_DISPLAYONLY_VSYNC
     * (5). Both requests control the same physical vertical-retrace source;
     * the ISR continues to notify dxgkrnl with DISPLAYONLY_VSYNC.
     */
    if (interruptType != DXGK_INTERRUPT_CRTC_VSYNC &&
        interruptType != DXGK_INTERRUPT_DISPLAYONLY_VSYNC) {
        finalStatus = STATUS_NOT_IMPLEMENTED;
        RpRecordControlInterruptResult(
            a, interruptType, enableInterrupt, synchronizeStatus, FALSE,
            FALSE, finalStatus);
        RP_LOG("ControlInterrupt unsupported type=%u enable=%u final=0x%08lx\n",
               (UINT)interruptType, enableInterrupt, finalStatus);
        return finalStatus;
    }

    if (!a->VSyncHardwareReady || !a->PixelValveRegs ||
        !InterlockedCompareExchange(&a->Active, 0, 0) ||
        !a->Dxgk.DeviceHandle) {
        finalStatus = STATUS_DEVICE_NOT_READY;
        RpRecordControlInterruptResult(
            a, interruptType, enableInterrupt, synchronizeStatus, FALSE,
            FALSE, finalStatus);
        return finalStatus;
    }

    control.Adapter = a;
    control.Enable = enableInterrupt;
    control.ProvisionalQpc = 0;
    if (enableInterrupt) {
        seed = KeQueryPerformanceCounter(NULL);
        if (seed.QuadPart <= 0) {
            finalStatus = STATUS_DEVICE_CONFIGURATION_ERROR;
            RpRecordControlInterruptResult(
                a, interruptType, enableInterrupt, synchronizeStatus, FALSE,
                FALSE, finalStatus);
            return finalStatus;
        }
        control.ProvisionalQpc = seed.QuadPart;
    }

    if (a->Dxgk.DxgkCbSynchronizeExecution) {
        synchronizeStatus = a->Dxgk.DxgkCbSynchronizeExecution(
            a->Dxgk.DeviceHandle,
            RpSetVSyncSynchronized,
            &control,
            0,
            &synchronized);
        if (NT_SUCCESS(synchronizeStatus) && synchronized) {
            applied = TRUE;
        } else if (synchronizeStatus == STATUS_UNSUCCESSFUL) {
            /*
             * Microsoft documents STATUS_UNSUCCESSFUL when execution cannot be
             * synchronized, including when the interrupt is not connected yet.
             * INTEN is not touched by our ISR, so applying this tiny mask update
             * directly is race-safe and lets a later-connected IRQ see VFP_START.
             */
            usedDirectFallback = TRUE;
            InterlockedIncrement64(&a->VSyncControlDirectFallbacks);
            applied = RpSetVSyncSynchronized(&control);
        }
    } else {
        /*
         * Keep the same narrow direct path if the callback is absent from the
         * copied interface. The resulting condition is persisted explicitly.
         */
        usedDirectFallback = TRUE;
        InterlockedIncrement64(&a->VSyncControlDirectFallbacks);
        applied = RpSetVSyncSynchronized(&control);
    }

    if (applied) {
        finalStatus = STATUS_SUCCESS;
    } else if (NT_SUCCESS(synchronizeStatus)) {
        finalStatus = STATUS_UNSUCCESSFUL;
    } else {
        finalStatus = synchronizeStatus;
    }

    RpRecordControlInterruptResult(
        a, interruptType, enableInterrupt, synchronizeStatus, synchronized,
        usedDirectFallback, finalStatus);

    RP_LOG("ControlInterrupt VSYNC type=%u enable=%u pv=%lu syncStatus=0x%08lx syncReturn=%u fallback=%u final=0x%08lx inten=0x%08lx intstat=0x%08lx\n",
           (UINT)interruptType, enableInterrupt, a->PixelValveIndex, synchronizeStatus,
           synchronized, usedDirectFallback, finalStatus,
           READ_REGISTER_ULONG((PULONG)RpPvRegister(a, RP_PV_INTEN)),
           READ_REGISTER_ULONG((PULONG)RpPvRegister(a, RP_PV_INTSTAT)));
    return finalStatus;
}

NTSTATUS APIENTRY RpGetScanLine(
    CONST HANDLE context,
    DXGKARG_GETSCANLINE *scan)
{
    RP_ADAPTER *a = (RP_ADAPTER *)context;
    LONG64 last;
    LARGE_INTEGER now;
    ULONG line;
    LONG phaseSource;
    int inBlank;

    PAGED_CODE();

    if (!a || !scan || scan->VidPnTargetId != 0) {
        return STATUS_INVALID_PARAMETER;
    }
    if (!a->VSyncHardwareReady || !a->FirmwareTimingValid) {
        return STATUS_DEVICE_NOT_READY;
    }

    last = InterlockedCompareExchange64(&a->LastVSyncQpc, 0, 0);
    phaseSource = InterlockedCompareExchange(&a->VSyncPhaseSource, 0, 0);
    if (last == 0 || phaseSource == RP_VSYNC_PHASE_NONE) {
        return STATUS_DEVICE_NOT_READY;
    }

    if (phaseSource == RP_VSYNC_PHASE_HARDWARE &&
        InterlockedCompareExchange(&a->VSyncAnchorReported, 1, 0) == 0) {
        ULONGLONG anchor = (ULONGLONG)last;
        ULONGLONG count = (ULONGLONG)InterlockedCompareExchange64(
            &a->VSyncCount, 0, 0);
        RpWriteDeviceDword(a, L"Rpi5DisplayVSyncAnchorReady", 1);
        RpWriteDeviceDword(a, L"Rpi5DisplayVSyncAnchorQpcLow", (ULONG)anchor);
        RpWriteDeviceDword(a, L"Rpi5DisplayVSyncAnchorQpcHigh",
                           (ULONG)(anchor >> 32));
        RpWriteDeviceDword(a, L"Rpi5DisplayVSyncInterruptsLow", (ULONG)count);
        RpWriteDeviceDword(a, L"Rpi5DisplayVSyncInterruptsHigh",
                           (ULONG)(count >> 32));
        RP_LOG("VSync: first Windows-enabled hardware anchor observed pv=%lu qpc=%lld interrupts=%lld\n",
               a->PixelValveIndex, last, (LONG64)count);
    } else if (phaseSource == RP_VSYNC_PHASE_PROVISIONAL &&
               InterlockedCompareExchange(
                   &a->VSyncProvisionalReported, 1, 0) == 0) {
        RpWriteDeviceDword(a, L"Rpi5DisplayVSyncProvisionalPhaseUsed", 1);
        RP_LOG("VSync: GetScanLine using provisional timing phase pv=%lu qpc=%lld\n",
               a->PixelValveIndex, last);
    }

    now = KeQueryPerformanceCounter(NULL);
    if (!rp_vsync_scanline_from_qpc(
            (ULONGLONG)a->QpcFrequency,
            (ULONGLONG)last,
            (ULONGLONG)now.QuadPart,
            a->FirmwareDisplay.timing.clock_khz,
            a->FirmwareDisplay.timing.htotal,
            a->FirmwareDisplay.timing.vdisplay,
            a->FirmwareDisplay.timing.vtotal,
            &line,
            &inBlank)) {
        return STATUS_DEVICE_NOT_READY;
    }

    scan->InVerticalBlank = inBlank ? TRUE : FALSE;
    scan->ScanLine = inBlank ? 0u : line;
    InterlockedIncrement64(&a->ScanLineQueries);
    if (phaseSource == RP_VSYNC_PHASE_PROVISIONAL) {
        InterlockedIncrement64(&a->VSyncProvisionalScanLineQueries);
    }
    return STATUS_SUCCESS;
}

BOOLEAN NTAPI RpInterrupt(PVOID context, ULONG messageNumber)
{
    RP_ADAPTER *a = (RP_ADAPTER *)context;
    DXGKARGCB_NOTIFY_INTERRUPT_DATA notify;
    ULONG status;
    LARGE_INTEGER now;

    UNREFERENCED_PARAMETER(messageNumber);

    if (!a || !a->VSyncHardwareReady || !a->PixelValveRegs ||
        !InterlockedCompareExchange(&a->Active, 0, 0) ||
        !InterlockedCompareExchange(&a->VSyncInterruptEnabled, 0, 0)) {
        return FALSE;
    }

    status = READ_REGISTER_ULONG((PULONG)RpPvRegister(a, RP_PV_INTSTAT));
    if ((status & RP_PV_INT_VFP_START) == 0) {
        return FALSE;
    }

    now = KeQueryPerformanceCounter(NULL);

    WRITE_REGISTER_ULONG((PULONG)RpPvRegister(a, RP_PV_INTSTAT),
                         RP_PV_INT_VFP_START);
    KeMemoryBarrier();

    /*
     * The first real VFP_START replaces the provisional phase, and every later
     * edge refreshes the hardware anchor. Count it before notifying dxgkrnl so
     * StopDevice can preserve proof that the ISR was actually reached.
     */
    InterlockedExchange64(&a->LastVSyncQpc, now.QuadPart);
    InterlockedExchange(&a->VSyncPhaseSource, RP_VSYNC_PHASE_HARDWARE);
    /*
     * Do not reset VSyncAnchorReported here. RpGetScanLine consumes it as a
     * one-shot diagnostic latch. Re-arming it on every ~60 Hz VFP edge turns
     * GetScanLine into continuous registry I/O and ETW/debug logging.
     */
    InterlockedIncrement64(&a->VSyncCount);

    RtlZeroMemory(&notify, sizeof(notify));
    notify.InterruptType = DXGK_INTERRUPT_DISPLAYONLY_VSYNC;
    notify.DisplayOnlyVsync.VidPnTargetId = 0;
    a->Dxgk.DxgkCbNotifyInterrupt(a->Dxgk.DeviceHandle, &notify);
    (VOID)a->Dxgk.DxgkCbQueueDpc(a->Dxgk.DeviceHandle);
    return TRUE;
}
