/* SPDX-License-Identifier: GPL-3.0-only
 * BCM2712 PixelValve VSync support for the display-only driver.
 *
 * This file intentionally does not program display modes, HVS lists, HDMI, or
 * V3D. It only uses the PixelValve VFP-start interrupt already generated by
 * the firmware-configured scanout, and derives scan-line position from that
 * real hardware VSync anchor plus the validated firmware timing.
 */
#include "display.h"

#define RP_PV_MMIO_BYTES              0x100u
#define RP_PV0_PHYS                   0x107c410000ULL
#define RP_PV1_PHYS                   0x107c411000ULL
#define RP_PV_V_CONTROL               0x04u
#define RP_PV_VCONTROL_VIDEN          (1u << 0)
#define RP_PV_INTEN                   0x24u
#define RP_PV_INTSTAT                 0x28u
#define RP_PV_INT_VFP_START           (1u << 7)
#define RP_VSYNC_PRIME_DELAY_US       50u
#define RP_VSYNC_PRIME_ATTEMPTS       2000u

static GUID gRpDisplayHandoffGuid =
    { 0x941ce3d8, 0x8c4f, 0x4b9e, { 0xa5, 0x77, 0x1c, 0xc9, 0x82, 0x74, 0x55, 0x31 } };

static volatile ULONG *RpPvRegister(RP_ADAPTER *a, ULONG offset)
{
    return (volatile ULONG *)((volatile UCHAR *)a->PixelValveRegs + offset);
}

static VOID RpWriteDeviceDword(RP_ADAPTER *a, PCWSTR valueName, ULONG value)
{
    HANDLE key;
    UNICODE_STRING name;

    if (!a || !a->Pdo ||
        !NT_SUCCESS(IoOpenDeviceRegistryKey(a->Pdo, PLUGPLAY_REGKEY_DEVICE,
                                             KEY_SET_VALUE, &key))) {
        return;
    }

    RtlInitUnicodeString(&name, valueName);
    (VOID)ZwSetValueKey(key, &name, 0, REG_DWORD, &value, sizeof(value));
    ZwClose(key);
}

static VOID RpRecordVSyncCounters(RP_ADAPTER *a)
{
    ULONGLONG count;
    ULONGLONG queries;

    if (!a) return;
    count = (ULONGLONG)InterlockedCompareExchange64(&a->VSyncCount, 0, 0);
    queries = (ULONGLONG)InterlockedCompareExchange64(&a->ScanLineQueries, 0, 0);
    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncInterruptsLow", (ULONG)count);
    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncInterruptsHigh", (ULONG)(count >> 32));
    RpWriteDeviceDword(a, L"Rpi5DisplayScanLineQueriesLow", (ULONG)queries);
    RpWriteDeviceDword(a, L"Rpi5DisplayScanLineQueriesHigh", (ULONG)(queries >> 32));
}

BOOLEAN RpVSyncRegistrationAvailable(VOID)
{
    RP_DISPLAY_HANDOFF handoff;
    UNICODE_STRING name = RTL_CONSTANT_STRING(L"Rpi5DisplayHandoff");
    ULONG bytes = sizeof(handoff);
    ULONG attributes = 0;
    NTSTATUS status;

    RtlZeroMemory(&handoff, sizeof(handoff));
    status = ExGetFirmwareEnvironmentVariable(
        &name, &gRpDisplayHandoffGuid, &handoff, &bytes, &attributes);

    if (!NT_SUCCESS(status) ||
        bytes != sizeof(handoff) ||
        !rp_display_handoff_attributes_valid(attributes) ||
        !rp_display_handoff_valid(&handoff,
                                  handoff.timing.hdisplay,
                                  handoff.timing.vdisplay)) {
        return FALSE;
    }

    /* This first hardware implementation is intentionally limited to Pi 5 HDMI. */
    return handoff.display_number == 2u || handoff.display_number == 7u;
}

static PCM_PARTIAL_RESOURCE_DESCRIPTOR RpFindMemoryResource(
    PCM_RESOURCE_LIST list,
    ULONGLONG expectedBase,
    ULONG minimumLength)
{
    ULONG fullIndex;
    ULONG partialIndex;

    if (!list) return NULL;

    for (fullIndex = 0; fullIndex < list->Count; ++fullIndex) {
        PCM_FULL_RESOURCE_DESCRIPTOR full = &list->List[fullIndex];
        PCM_PARTIAL_RESOURCE_LIST partial = &full->PartialResourceList;

        for (partialIndex = 0; partialIndex < partial->Count; ++partialIndex) {
            PCM_PARTIAL_RESOURCE_DESCRIPTOR descriptor =
                &partial->PartialDescriptors[partialIndex];

            if (descriptor->Type != CmResourceTypeMemory) continue;
            if ((ULONGLONG)descriptor->u.Memory.Start.QuadPart != expectedBase) continue;
            if (descriptor->u.Memory.Length < minimumLength) continue;
            return descriptor;
        }
    }

    return NULL;
}

static NTSTATUS RpPrimeVSyncAnchor(RP_ADAPTER *a)
{
    ULONG attempt;

    /* Clear a stale VFP-start status before waiting for a fresh hardware edge. */
    WRITE_REGISTER_ULONG((PULONG)RpPvRegister(a, RP_PV_INTSTAT), RP_PV_INT_VFP_START);
    KeMemoryBarrier();

    for (attempt = 0; attempt < RP_VSYNC_PRIME_ATTEMPTS; ++attempt) {
        ULONG status = READ_REGISTER_ULONG((PULONG)RpPvRegister(a, RP_PV_INTSTAT));
        if (status & RP_PV_INT_VFP_START) {
            LARGE_INTEGER now = KeQueryPerformanceCounter(NULL);
            WRITE_REGISTER_ULONG((PULONG)RpPvRegister(a, RP_PV_INTSTAT),
                                 RP_PV_INT_VFP_START);
            KeMemoryBarrier();
            InterlockedExchange64(&a->LastVSyncQpc, now.QuadPart);
            return STATUS_SUCCESS;
        }
        KeStallExecutionProcessor(RP_VSYNC_PRIME_DELAY_US);
    }

    return STATUS_IO_TIMEOUT;
}

NTSTATUS RpVSyncInitialize(RP_ADAPTER *a, PCM_RESOURCE_LIST resources)
{
    ULONGLONG expectedBase;
    PCM_PARTIAL_RESOURCE_DESCRIPTOR descriptor;
    LARGE_INTEGER frequency;
    ULONG vcontrol;
    NTSTATUS status;

    if (!a || !a->VSyncAdvertised || !a->FirmwareTimingValid) {
        return STATUS_DEVICE_CONFIGURATION_ERROR;
    }

    if (a->FirmwareDisplay.display_number == 2u) {
        expectedBase = RP_PV0_PHYS;
        a->PixelValveIndex = 0;
    } else if (a->FirmwareDisplay.display_number == 7u) {
        expectedBase = RP_PV1_PHYS;
        a->PixelValveIndex = 1;
    } else {
        return STATUS_NOT_SUPPORTED;
    }

    descriptor = RpFindMemoryResource(resources, expectedBase, RP_PV_MMIO_BYTES);
    if (!descriptor) {
        RP_LOG("VSync: assigned PixelValve MMIO resource 0x%llx not found\n",
               expectedBase);
        return STATUS_DEVICE_CONFIGURATION_ERROR;
    }

    a->PixelValveRegs = MmMapIoSpaceEx(
        descriptor->u.Memory.Start,
        RP_PV_MMIO_BYTES,
        PAGE_READWRITE | PAGE_NOCACHE);
    if (!a->PixelValveRegs) {
        return STATUS_NO_MEMORY;
    }
    a->PixelValveBytes = RP_PV_MMIO_BYTES;

    vcontrol = READ_REGISTER_ULONG((PULONG)RpPvRegister(a, RP_PV_V_CONTROL));
    if ((vcontrol & RP_PV_VCONTROL_VIDEN) == 0) {
        RP_LOG("VSync: PixelValve%lu is not scanning out (V_CONTROL=0x%08lx)\n",
               a->PixelValveIndex, vcontrol);
        MmUnmapIoSpace(a->PixelValveRegs, a->PixelValveBytes);
        a->PixelValveRegs = NULL;
        a->PixelValveBytes = 0;
        return STATUS_DEVICE_NOT_READY;
    }

    /* Start with the hardware interrupt disabled until dxgkrnl requests it. */
    WRITE_REGISTER_ULONG(
        (PULONG)RpPvRegister(a, RP_PV_INTEN),
        READ_REGISTER_ULONG((PULONG)RpPvRegister(a, RP_PV_INTEN)) &
            ~RP_PV_INT_VFP_START);
    WRITE_REGISTER_ULONG((PULONG)RpPvRegister(a, RP_PV_INTSTAT),
                         RP_PV_INT_VFP_START);
    KeMemoryBarrier();

    (VOID)KeQueryPerformanceCounter(&frequency);
    a->QpcFrequency = frequency.QuadPart;
    if (a->QpcFrequency <= 0) {
        MmUnmapIoSpace(a->PixelValveRegs, a->PixelValveBytes);
        a->PixelValveRegs = NULL;
        a->PixelValveBytes = 0;
        return STATUS_DEVICE_CONFIGURATION_ERROR;
    }

    status = RpPrimeVSyncAnchor(a);
    if (!NT_SUCCESS(status)) {
        RP_LOG("VSync: no PixelValve VFP-start edge observed, status=0x%08lx\n",
               status);
        MmUnmapIoSpace(a->PixelValveRegs, a->PixelValveBytes);
        a->PixelValveRegs = NULL;
        a->PixelValveBytes = 0;
        return status;
    }

    InterlockedExchange(&a->VSyncInterruptEnabled, 0);
    InterlockedExchange64(&a->VSyncCount, 0);
    InterlockedExchange64(&a->ScanLineQueries, 0);
    a->VSyncHardwareReady = TRUE;

    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncAdvertised", 1);
    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncHardwareReady", 1);
    RpWriteDeviceDword(a, L"Rpi5DisplayPixelValveIndex", a->PixelValveIndex);
    RpWriteDeviceDword(a, L"Rpi5DisplayPixelValvePhysLow", (ULONG)expectedBase);
    RpWriteDeviceDword(a, L"Rpi5DisplayPixelValvePhysHigh",
                       (ULONG)(expectedBase >> 32));

    RP_LOG("VSync: hardware ready display=%lu pv=%lu base=0x%llx qpcHz=%lld\n",
           a->FirmwareDisplay.display_number, a->PixelValveIndex,
           expectedBase, a->QpcFrequency);
    return STATUS_SUCCESS;
}

static BOOLEAN RpDisableVSyncSynchronized(PVOID context)
{
    RP_ADAPTER *a = (RP_ADAPTER *)context;
    ULONG enable;

    if (!a || !a->PixelValveRegs) return TRUE;

    enable = READ_REGISTER_ULONG((PULONG)RpPvRegister(a, RP_PV_INTEN));
    WRITE_REGISTER_ULONG((PULONG)RpPvRegister(a, RP_PV_INTEN),
                         enable & ~RP_PV_INT_VFP_START);
    WRITE_REGISTER_ULONG((PULONG)RpPvRegister(a, RP_PV_INTSTAT),
                         RP_PV_INT_VFP_START);
    KeMemoryBarrier();
    InterlockedExchange(&a->VSyncInterruptEnabled, 0);
    return TRUE;
}

VOID RpVSyncShutdown(RP_ADAPTER *a)
{
    BOOLEAN synchronized = FALSE;

    if (!a || !a->PixelValveRegs) return;

    RpRecordVSyncCounters(a);

    if (a->Dxgk.DxgkCbSynchronizeExecution && a->Dxgk.DeviceHandle) {
        NTSTATUS status = a->Dxgk.DxgkCbSynchronizeExecution(
            a->Dxgk.DeviceHandle,
            RpDisableVSyncSynchronized,
            a,
            0,
            &synchronized);
        if (!NT_SUCCESS(status) || !synchronized) {
            RpDisableVSyncSynchronized(a);
        }
    } else {
        RpDisableVSyncSynchronized(a);
    }

    a->VSyncHardwareReady = FALSE;
    MmUnmapIoSpace(a->PixelValveRegs, a->PixelValveBytes);
    a->PixelValveRegs = NULL;
    a->PixelValveBytes = 0;
    RpWriteDeviceDword(a, L"Rpi5DisplayVSyncHardwareReady", 0);
}

NTSTATUS APIENTRY RpControlInterrupt(
    CONST HANDLE context,
    CONST DXGK_INTERRUPT_TYPE interruptType,
    BOOLEAN enableInterrupt)
{
    RP_ADAPTER *a = (RP_ADAPTER *)context;
    ULONG enable;

    if (!a) return STATUS_INVALID_PARAMETER;
    /*
     * The legacy ControlInterrupt DDI requests CRTC_VSYNC. KMDODs report the
     * corresponding hardware event back with DISPLAYONLY_VSYNC.
     */
    if (interruptType != DXGK_INTERRUPT_CRTC_VSYNC) {
        return STATUS_NOT_IMPLEMENTED;
    }
    if (!a->VSyncHardwareReady || !a->PixelValveRegs ||
        !InterlockedCompareExchange(&a->Active, 0, 0)) {
        return STATUS_DEVICE_NOT_READY;
    }

    enable = READ_REGISTER_ULONG((PULONG)RpPvRegister(a, RP_PV_INTEN));
    if (enableInterrupt) {
        WRITE_REGISTER_ULONG((PULONG)RpPvRegister(a, RP_PV_INTSTAT),
                             RP_PV_INT_VFP_START);
        WRITE_REGISTER_ULONG((PULONG)RpPvRegister(a, RP_PV_INTEN),
                             enable | RP_PV_INT_VFP_START);
        InterlockedExchange(&a->VSyncInterruptEnabled, 1);
    } else {
        WRITE_REGISTER_ULONG((PULONG)RpPvRegister(a, RP_PV_INTEN),
                             enable & ~RP_PV_INT_VFP_START);
        WRITE_REGISTER_ULONG((PULONG)RpPvRegister(a, RP_PV_INTSTAT),
                             RP_PV_INT_VFP_START);
        InterlockedExchange(&a->VSyncInterruptEnabled, 0);
    }
    KeMemoryBarrier();

    RP_LOG("ControlInterrupt CRTC_VSYNC enable=%u pv=%lu\n",
           enableInterrupt, a->PixelValveIndex);
    return STATUS_SUCCESS;
}

NTSTATUS APIENTRY RpGetScanLine(
    CONST HANDLE context,
    DXGKARG_GETSCANLINE *scan)
{
    RP_ADAPTER *a = (RP_ADAPTER *)context;
    LONG64 last;
    LARGE_INTEGER now;
    ULONG line;
    int inBlank;

    PAGED_CODE();

    if (!a || !scan || scan->VidPnTargetId != 0) {
        return STATUS_INVALID_PARAMETER;
    }
    if (!a->VSyncHardwareReady || !a->FirmwareTimingValid) {
        return STATUS_DEVICE_NOT_READY;
    }

    last = InterlockedCompareExchange64(&a->LastVSyncQpc, 0, 0);
    now = KeQueryPerformanceCounter(NULL);
    if (!rp_vsync_scanline_from_qpc(
            (ULONGLONG)a->QpcFrequency,
            (ULONGLONG)last,
            (ULONGLONG)now.QuadPart,
            a->FirmwareDisplay.timing.clock_khz,
            a->FirmwareDisplay.timing.htotal,
            a->FirmwareDisplay.timing.vdisplay,
            a->FirmwareDisplay.timing.vtotal,
            &line,
            &inBlank)) {
        return STATUS_DEVICE_NOT_READY;
    }

    scan->InVerticalBlank = inBlank ? TRUE : FALSE;
    scan->ScanLine = inBlank ? 0u : line;
    InterlockedIncrement64(&a->ScanLineQueries);
    return STATUS_SUCCESS;
}

BOOLEAN NTAPI RpInterrupt(PVOID context, ULONG messageNumber)
{
    RP_ADAPTER *a = (RP_ADAPTER *)context;
    DXGKARGCB_NOTIFY_INTERRUPT_DATA notify;
    ULONG status;
    LARGE_INTEGER now;

    UNREFERENCED_PARAMETER(messageNumber);

    if (!a || !a->VSyncHardwareReady || !a->PixelValveRegs ||
        !InterlockedCompareExchange(&a->Active, 0, 0) ||
        !InterlockedCompareExchange(&a->VSyncInterruptEnabled, 0, 0)) {
        return FALSE;
    }

    status = READ_REGISTER_ULONG((PULONG)RpPvRegister(a, RP_PV_INTSTAT));
    if ((status & RP_PV_INT_VFP_START) == 0) {
        return FALSE;
    }

    now = KeQueryPerformanceCounter(NULL);
    InterlockedExchange64(&a->LastVSyncQpc, now.QuadPart);

    WRITE_REGISTER_ULONG((PULONG)RpPvRegister(a, RP_PV_INTSTAT),
                         RP_PV_INT_VFP_START);
    KeMemoryBarrier();

    RtlZeroMemory(&notify, sizeof(notify));
    notify.InterruptType = DXGK_INTERRUPT_DISPLAYONLY_VSYNC;
    notify.DisplayOnlyVsync.VidPnTargetId = 0;
    a->Dxgk.DxgkCbNotifyInterrupt(a->Dxgk.DeviceHandle, &notify);
    (VOID)a->Dxgk.DxgkCbQueueDpc(a->Dxgk.DeviceHandle);
    InterlockedIncrement64(&a->VSyncCount);
    return TRUE;
}
